/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_aexolgl_android_hdw_HDWBridge */

#ifndef _Included_com_aexolgl_android_hdw_HDWBridge
#define _Included_com_aexolgl_android_hdw_HDWBridge
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_aexolgl_android_hdw_HDWBridge
 * Method:    nativeOnSensorChanged
 * Signature: ([FJ)V
 */
JNIEXPORT void JNICALL Java_com_aexolgl_android_hdw_HDWBridge_nativeOnSensorChanged
  (JNIEnv *, jclass, jfloatArray, jlong);

#ifdef __cplusplus
}
#endif
#endif
