/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_aexolgl_android_fb_FBBridge */

#ifndef _Included_com_aexolgl_android_fb_FBBridge
#define _Included_com_aexolgl_android_fb_FBBridge
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_aexolgl_android_fb_FBBridge
 * Method:    fbLoginResultCallback
 * Signature: (ILjava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_aexolgl_android_fb_FBBridge_fbLoginResultCallback
  (JNIEnv *, jclass, jint, jstring, jstring, jstring, jlong);

  /*
   * Class:     com_aexolgl_android_fb_FBBridge
   * Method:    fbRequestGETResultCallback
   * Signature: (ILjava/lang/String;Ljava/lang/String;J)V
   */
  JNIEXPORT void JNICALL Java_com_aexolgl_android_fb_FBBridge_fbRequestGETResultCallback
    (JNIEnv *, jclass, jint, jstring, jstring, jlong);

  /*
   * Class:     com_aexolgl_android_fb_FBBridge
   * Method:    fbRequestDELETEResultCallback
   * Signature: (ILjava/lang/String;J)V
   */
  JNIEXPORT void JNICALL Java_com_aexolgl_android_fb_FBBridge_fbRequestDELETEResultCallback
    (JNIEnv *, jclass, jint, jstring, jlong);

#ifdef __cplusplus
}
#endif
#endif
