/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_aexol_camera_jni_NativeCameraLib */

#ifndef _Included_com_aexol_camera_jni_NativeCameraLib
#define _Included_com_aexol_camera_jni_NativeCameraLib
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_aexol_camera_jni_NativeCameraLib
 * Method:    nativeInit
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_com_aexolgl_android_camera_NativeCameraLib_nativeInit
(JNIEnv *, jclass, jint, jint, jint);

/*
 * Class:     com_aexol_camera_jni_NativeCameraLib
 * Method:    nativeSetTransformMatrix
 * Signature: ([F)V
 */
JNIEXPORT void JNICALL Java_com_aexolgl_android_camera_NativeCameraLib_nativeSetTransformMatrix
(JNIEnv *, jclass, jfloatArray, jint);

/*
 * Class:     com_aexol_camera_jni_NativeCameraLib
 * Method:    nativeDraw
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_aexolgl_android_camera_NativeCameraLib_nativeDraw
(JNIEnv *, jclass);

JNIEXPORT void JNICALL Java_com_aexolgl_android_camera_NativeCameraLib_nativeOnNewCameraFrame
(JNIEnv *, jclass, jint);

#ifdef __cplusplus
}


#endif
#endif
