#Custom modules search
cmake_policy(PUSH)
cmake_policy(SET CMP0012 NEW)
include("${CMAKE_CURRENT_LIST_DIR}/AexolGLTargets.cmake")
if(@BUILD_FOR_GLES2@)
    find_package(OpenGLES2 REQUIRED)
    set(_l_gl_inc ${OPENGLES2_INCLUDE_DIR})
elseif(@BUILD_FOR_GLES3@)
    find_package(OpenGLES3 REQUIRED)
    set(_l_gl_inc  ${OPENGLES3_INCLUDE_DIR})
else()
    find_package(OpenGL REQUIRED)
    set(_l_gl_inc  ${OPENGL_INCLUDE_DIR})
endif()
get_target_property(_iinterface AexolGL::AexolGL INTERFACE_INCLUDE_DIRECTORIES)
set_target_properties(AexolGL::AexolGL PROPERTIES
    INTERFACE_INCLUDE_DIRECTORIES "${_iinterface};${_l_gl_inc}")
if(TARGET AexolGL::AexolGLStatic)
    get_target_property(_iinterface AexolGL::AexolGLStatic INTERFACE_INCLUDE_DIRECTORIES)
    set_target_properties(AexolGL::AexolGLStatic PROPERTIES
        INTERFACE_INCLUDE_DIRECTORIES "${_iinterface};${_l_gl_inc}")
endif()
unset(_l_gl_inc)
cmake_policy(POP)
